config/routes.rb
Rails.application.routes.draw do

  root to: 'addresses#index'

  resources :addresses, only: [:index, :new, :create] 
  resources :estimations, only: [:new, :create, :show]

end

app/models/address.rb
class Address < ApplicationRecord
  with_options presence: true do
    validates :municipality, :house_number, :prefecture
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
    validates :phone_number, length: { maximum: 11 }, exclusion: { in: %w[-] }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ceilling.rb
class Ceilling < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '屋根も含む' },
    { id: 3, name: '屋根は含まない' },
  ]

  include ActiveHash::Associations
  has_many :estimations
end

app/models/estimation.rb
class Estimation < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :wide
  belongs_to :ceilling
  belongs_to :grade

  validates :wide_id, :ceilling_id, :grade_id, numericality: { other_than: 1, message: "を選択してください" }


  def area_price
    if self.wide_id == 2
      30000
    elsif self.wide_id == 3
      50000
    elsif self.wide_id == 4
      80000
    elsif self.wide_id == 5
      150000
    end
  end

  def sum_price
    if self.ceilling_id == 2 && self.grade_id== 2
      area_price + ( area_price * 2 / 3 ) 
    elsif self.ceilling_id == 3 && self.grade_id== 2
      area_price
    elsif self.ceilling_id == 2 && self.grade_id== 3
      ( area_price * 1.5 ) + ( area_price * 2 / 3 )
    elsif self.ceilling_id == 3 && self.grade_id== 3
      ( area_price * 1.5 ) 
    end
  end
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '通常グレード' },
    { id: 3, name: 'ハイグレード' },
  ]

  include ActiveHash::Associations
  has_many :estimations
end

app/models/wide.rb
class Wide < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '６畳' },
    { id: 3, name: '８畳' },
    { id: 4, name: '10畳' },
    { id: 5, name: '20畳' },
  ]

  include ActiveHash::Associations
  has_many :estimations
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      render :create
    else
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:name, :email, :postal_code, :prefecture, :municipality, :house_number, :building_name, :phone_number, :request)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estimations_controller.rb
class EstimationsController < ApplicationController
  def new
    @estimation = Estimation.new
  end

  def create
    @estimation = Estimation.new(estimation_params)
    if @estimation.save
      redirect_to @estimation
    else
      render :new
    end
  end

  def show
    @estimation = Estimation.find(params[:id])
    @area_price = @estimation.area_price
    @sum_price = @estimation.sum_price
  end

  private

  def estimation_params
    params.require(:estimation).permit(:wide_id, :ceilling_id, :grade_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimations_helper.rb
module EstimationsHelper
end

app/views/addresses/create.html.erb
<div class="create">
  <div class="success">
    <h3>申し込みありがとうございます。</h3>
    <h3>記入いただいたemailに後日連絡させていただきます。</h3>
    <a class="btn" href="/">Homeへ戻る</a>
  </div>
</div>

app/views/addresses/index.html.erb
<div class="lp-block-1">
    <h2 class="lp-title-1">壁紙が違うだけで世界が変わります</h2>
    <p class="lp-text">あなたの家の壁紙をどこよりも安く修繕・リフォームしてみませんか？</p>
    <div class="lp-button">
        <%= link_to '簡単10秒見積もりはこちら', new_estimation_path, class: "lp-button-a" %>
        <%= link_to '訪問見積もり予約はこちら', new_address_path, class: "lp-button-a" %>
    </div>
</div>


<div class="lp-band">
    <h2 class="lp-title-2">詳細はこちら</h2>
    <p class="lp-text">↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓</p>
</div>

<div class="lp-block-2">
</div>
<h2 class="lp-title-2">仲介がないためWin-Winの関係</h2>
<div class="lp-button">
        <%= link_to '簡単10秒見積もりはこちら', new_estimation_path, class: "lp-button-a" %>
        <%= link_to '訪問見積もり予約はこちら', new_address_path, class: "lp-button-a" %>
</div>

<hr class="lp-line">

<h2 class="lp-title-2">活動実績</h2>
<a class="twitter-timeline" href="https://twitter.com/4DeHyipyboj3FYA?ref_src=twsrc%5Etfw">Tweets by TwitterDev</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    
<hr class="lp-line">


<div class="lp-block">
    <h2 class="lp-title-1">約束いたします</h2>
    <p class="lp-text">私に任せて貰えば以下の要件を約束します。</p>
    <ul class="lp-list">
        <li class="lp-item">納期までに必ず仕上げます。</li>
        <li class="lp-item">どこよりもリーズナブルな値段設定です。</li>
        <li class="lp-item">お部屋の養生もきちんと行います。</li>
        <li class="lp-item">満足いかない箇所は無料修繕いたします。</li>
        <li class="lp-item">新しい空間を提供いたします。</li>
    </ul>
    <div class="lp-button">
        <%= link_to '簡単10秒見積もりはこちら', new_estimation_path, class: "lp-button-a" %>
        <%= link_to '訪問見積もり予約はこちら', new_address_path, class: "lp-button-a" %>
    </div>
</div>

app/views/addresses/new.html.erb
<%= form_with model: @address, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="Form">
    <h1 class="Form-Title">訪問見積もり申し込み </h1>
    <div class="Form-Item">
      <p class="Form-Item-Label">
        <span class="Form-Item-Label-Required">必須</span>お名前
      </p>
      <%= f.text_field :name, class:"Form-Item-Input", placeholder:"例）山田太郎" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>メールアドレス</p>
      <%= f.text_field :email, class:"Form-Item-Input", placeholder:"例）example@gmail.com" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>郵便番号</p>
      <%= f.text_field :postal_code, class:"Form-Item-Input", placeholder:"例）000-0000 ハイフンを含む" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>都道府県</p>
      <%= f.text_field :prefecture, class:"Form-Item-Input", placeholder:"例）群馬県" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>市区町村</p>
      <%= f.text_field :municipality, class:"Form-Item-Input", placeholder:"例）◯◯市◯◯町" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>番地</p>
      <%= f.text_field :house_number, class:"Form-Item-Input", placeholder:"例）1-1-1" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Any">任意</span>建物名</p>
      <%= f.text_field :building_name, class:"Form-Item-Input", placeholder:"例）◯◯ビル101" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>電話番号</p>
      <%= f.text_field :phone_number, class:"Form-Item-Input", placeholder:"例）00000000000 ハイフン不要" %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Any">任意</span>ご要望等</p>
      <%= f.text_area :request, class:"Form-Item-Textarea", placeholder:"不明点やご要望がございましたら記入ください。" %>
    </div>
    <%= f.submit "送信する" ,class:"Form-Btn" %>
  </div>
<% end %>

app/views/estimations/new.html.erb
<%= form_with model: @estimation, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div class="Form">
    <h1 class="Form-Title">簡単10秒見積もり </h1>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>部屋の広さ</p>
      <%= f.collection_select(:wide_id, Wide.all, :id, :name, {}, {class:"Form-Item-Input"}) %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>天井を含むか</p>
      <%= f.collection_select(:ceilling_id, Ceilling.all, :id, :name, {}, {class:"Form-Item-Input"}) %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>壁紙のグレード</p>
      <%= f.collection_select(:grade_id, Grade.all, :id, :name, {}, {class:"Form-Item-Input"}) %>
    </div>
    <%= f.submit "送信する" ,class:"Form-Btn" %>
  </div>
<% end %>

app/views/estimations/show.html.erb
<div class="Form">
  <div class="Form-Item">
    <p class="Form-Item-Label"><span class="Form-Item-Label-Required"></span>見積もり金額</p>
     <%= @estimation.sum_price %>
  </div>
</div>


  <div class="Form">
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>部屋の広さ</p>
      <%= @estimation.wide.name %>畳
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>天井を含むか</p>
      <%= @estimation.ceilling.name %>
    </div>
    <div class="Form-Item">
      <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>壁紙のグレード</p>
      <%= @estimation.grade.name %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Wallpaper</title>
    

</head>



  <body>
    <header class="site-header">
      <div class="wrapper site-header__wrapper">
        <a href="/" class="brand">クロスの張り替え申し込みサイト</a>
        <nav class="nav">
          <button class="nav__toggle" aria-expanded="false" type="button">
            menu
          </button>
          <ul class="nav__wrapper">
            <li class="nav__item"><a href="/">Home</a></li>
            <li class="nav__item"><a href="#">なぜ安いのか？</a></li>
            <li class="nav__item"><a href="#">壁紙サンプル</a></li>
            <li class="nav__item"><a href="#">実績</a></li>
            <li class="nav__item"><a href="#">Twitter</a></li>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer class="lp-sec-footer">
    <div class="lp-block">
        <small class="lp-copyright">&copy; 会社名</small>
    </div>
    </footer>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>